/* DaBin · separate screen entrypoints, one shared local capture store. */
(async()=>{
'use strict';
const M=DaBinModel,$=s=>document.querySelector(s),P=new URLSearchParams(location.search),today=M.dayKey(new Date());
const review=P.has('review');
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=n=>`<svg class="icon" aria-hidden="true"><use href="#i-${n}"/></svg>`;
const url=(page,params={})=>`${page}.html${Object.keys(params).length?'?'+new URLSearchParams(params):''}`;
const screen=document.body.dataset.screen,panel=$('#panel'),widget=$('#widget');
let entries,storageOK=true,filter=P.get('filter')||'all',day=P.get('day')||today,query=P.get('q')||'',timer,feedbackTimer,saving=false;
if(!/^\d{4}-\d{2}-\d{2}$/.test(day))day=today;
if(!['all','links','files','media'].includes(filter))filter='all';
try{entries=review?M.seed(today):JSON.parse(localStorage.getItem('dabin:v2:captures')||'null');if(!Array.isArray(entries)){entries=M.seed(today);localStorage.setItem('dabin:v2:captures',JSON.stringify(entries))}}catch{entries=M.seed(today);storageOK=false}
const persist=()=>{if(review)return;try{localStorage.setItem('dabin:v2:captures',JSON.stringify(entries.map(({objectURL,...e})=>e.fileId?{...e,preview:undefined}:e)))}catch{storageOK=false;throw Error('Browser storage is full or unavailable. This change could not be saved.')}};
const dayLabel=d=>d===today?'Today':d===M.shift(today,-1)?'Yesterday':new Date(d+'T12:00:00').toLocaleDateString('en',{weekday:'short',month:'short',day:'numeric'});
const fullDate=d=>new Date(d+'T12:00:00').toLocaleDateString('en',{weekday:'long',month:'long',day:'numeric',year:'numeric'});
const time=e=>new Date(e.capturedAt).toLocaleTimeString('en',{hour:'2-digit',minute:'2-digit',hour12:false});
const reminderLabel=v=>new Date(v).toLocaleString('en',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
const entryBy=id=>entries.find(e=>e.id===id);
const nav=(page,params)=>{location.href=url(page,params)};
const safeOriginal=s=>/^(https?:\/\/|assets\/|blob:)/.test(s||'');
const currentParams=()=>screen==='search'?{q:query,filter}:screen==='daily'?{day,filter}:{};
const detailURL=(e,focus='')=>url('detail',{id:e.id,from:screen,...currentParams(),...(focus?{focus}:{})});
function notice(message,entry){clearTimeout(feedbackTimer);$('#toast').hidden=false;$('#toast').innerHTML=`<span>${E(message)}</span>${entry?`<a href="${url('detail',{id:entry.id})}">View capture</a>`:''}<button aria-label="Dismiss message">×</button>`;$('#toast button').onclick=()=>$('#toast').hidden=true;feedbackTimer=setTimeout(()=>{$('#toast').hidden=true;widget.dataset.state='idle'},6000)}
function feedback(state,message,entry){widget.dataset.state=state;if(message)notice(message,entry)}
function head(title){return `<header class="panel-head"><div class="title-block"><h1>${title}</h1><span class="quiet-brand">DaBin</span></div><nav class="head-actions" aria-label="DaBin"><a class="icon-button" href="daily.html" title="Daily" aria-label="Daily" ${screen==='daily'?'aria-current="page"':''}>${icon('calendar')}</a><a class="icon-button" href="search.html" title="Search" aria-label="Search" ${screen==='search'?'aria-current="page"':''}>${icon('search')}</a><a class="icon-button" href="reminders.html" title="Reminders" aria-label="Reminders" ${screen==='reminders'?'aria-current="page"':''}>${icon('bell')}</a><button class="icon-button close-panel" title="Close" aria-label="Close panel">${icon('close')}</button></nav></header>`}
function filters(){return `<div class="filters" aria-label="Capture type">${['all','links','files','media'].map(f=>`<button class="filter" data-filter="${f}" aria-pressed="${f===filter}">${f[0].toUpperCase()+f.slice(1)}</button>`).join('')}</div>`}
const footer=count=>`<footer class="panel-foot"><span>${count===undefined?'Saved by capture day':count+' '+(count===1?'capture':'captures')}</span><a class="text-button" href="capture.html">${icon('plus')}Add capture</a></footer>`;
function fallback(e){return `<div class="thumb file-thumb">${icon(e.kind==='link'?'link':e.kind==='video'?'video':e.kind==='image'?'image':'file')}<span>${E(({ai:'AI',pdf:'PDF',video:'VIDEO',image:'IMAGE',document:'DOC',file:'FILE',link:'LINK'})[e.kind]||'TEXT')}</span></div>`}
function card(e,options={}){let note=e.kind==='text';return `<article class="capture-card ${note?'kind-note':''} ${options.featured?'featured':''} ${options.context?'context':''}" data-capture-id="${E(e.id)}">${options.context?'<p class="context-badge">Nearby capture</p>':''}${options.reminder?`<p class="reminder-date">${icon('bell')} ${E(reminderLabel(e.reminder))}</p>`:''}<a class="card-main" href="${detailURL(e)}">${e.preview?`<img class="thumb" src="${E(e.preview)}" alt="${E(e.title)}" loading="lazy">`:note?'':fallback(e)}<div class="card-copy"><div class="card-meta"><span>${E(e.source||e.kind)}${options.match?' · <span class="match-label">Match</span>':''}</span><time datetime="${E(e.capturedAt)}">${time(e)}</time></div><h3>${E(e.title)}</h3>${e.description?`<p class="card-description">${E(e.description)}</p>`:''}</div></a>${e.comment?`<p class="comment-excerpt">${E(e.comment)}</p>`:''}<div class="card-actions"><a href="${detailURL(e,'comment')}">${icon('comment')}${e.comment?'Edit comment':'Comment'}</a><a href="${detailURL(e,'reminder')}">${icon('bell')}${e.reminder?'Edit reminder':'Reminder'}</a></div>${options.reminder?`<p class="capture-origin">Captured ${E(dayLabel(e.day))} · <a href="${url('daily',{day:e.day})}">Go to day</a></p>`:''}</article>`}
const empty=(title,message,action='')=>`<div class="empty">${icon('bin')}<h2>${title}</h2><p>${message}</p>${action}</div>`;
function daily(){const all=M.ordered(entries.filter(e=>e.day===day)),list=all.filter(e=>filter==='all'||M.group(e)===filter);panel.innerHTML=head('Daily')+`<div class="date-row"><div class="date-label">${E(dayLabel(day))}<small>${new Date(day+'T12:00:00').toLocaleDateString('en',{month:'short',day:'numeric'})}</small></div><div class="date-controls">${day!==today?'<button class="today-link" id="today">Today</button>':''}<button class="icon-button" id="prev-day" aria-label="Previous day">${icon('left')}</button><label class="icon-button date-picker" title="Choose date">${icon('calendar')}<input class="calendar-input" type="date" id="day-picker" aria-label="Choose capture date" value="${day}" max="${today}"></label><button class="icon-button" id="next-day" aria-label="Next day" ${day>=today?'disabled':''}>${icon('right')}</button></div></div>`+filters()+`<div class="scroll" id="captures">${list.length?list.map((e,i)=>card(e,{featured:i===0&&!!e.preview})).join(''):all.length?empty('No '+filter+' on this day.','Your other captures are still here.','<button class="secondary" data-filter="all">Show all captures</button>'):empty('A little space for your day.','Nothing was captured on this date.',day===today?'<a class="secondary" href="capture.html">Add your first capture</a>':'<button class="secondary" id="empty-today">Back to today</button>')}</div>`+footer(list.length);$('#prev-day').onclick=()=>setDay(M.shift(day,-1));$('#next-day').onclick=()=>setDay(M.shift(day,1));$('#day-picker').onchange=e=>e.target.value&&setDay(e.target.value);['#today','#empty-today'].forEach(s=>{if($(s))$(s).onclick=()=>setDay(today)});bindCommon()}
function setDay(d){day=d;history.replaceState(null,'',url('daily',{day,filter}));daily()}
function search(){panel.innerHTML=head('Search')+`<label class="search-field">${icon('search')}<input id="query" type="search" placeholder="Find something you saved…" aria-label="Search all capture days" value="${E(query)}"><button class="icon-button" id="clear-query" aria-label="Clear search">${icon('close')}</button></label>`+filters()+'<div class="scroll" id="results" aria-live="polite"></div>'+footer();$('#query').oninput=e=>{query=e.target.value;renderResults();history.replaceState(null,'',url('search',{q:query,filter}))};$('#clear-query').onclick=()=>{$('#query').value='';query='';renderResults();$('#query').focus()};renderResults();bindCommon()}
function renderResults(){const groups=M.search(entries,query,filter),hits=groups.reduce((a,g)=>a+g.hits,0);$('#results').innerHTML=!query.trim()?empty('Your days, within reach.','Search titles, notes, comments or a date.'):!groups.length?empty('Nothing found for “'+E(query)+'”.','Try another word or a different filter.'):`<p class="search-summary">${hits} ${hits===1?'match':'matches'} · with nearby captures</p>`+groups.map(g=>`<section class="day-group"><h2 class="day-group-title">${E(fullDate(g.day))}</h2>${g.items.map(({entry,match})=>card(entry,{match,context:!match})).join('')}</section>`).join('')}
function reminders(){const list=entries.filter(e=>e.reminder).sort((a,b)=>a.reminder.localeCompare(b.reminder));panel.innerHTML=head('Reminders')+`<div class="scroll">${list.length?list.map(e=>card(e,{reminder:true})).join(''):empty('Nothing to remember just yet.','Add a reminder to any capture when you need it.')}</div>`+footer();bindCommon()}
function capture(){panel.classList.add('capture-panel');panel.innerHTML=head('Capture')+`<form class="capture-form" id="capture-form"><label class="form-label" for="paste">A thought, a link, anything.</label><textarea id="paste" placeholder="Paste here, or drop a file…" rows="5"></textarea><p class="hint">Saved to ${E(dayLabel(today).toLowerCase())}. No filing needed.</p><p class="error" id="capture-error" role="alert" hidden></p><div class="form-actions"><button class="text-button" id="choose-files" type="button">${icon('file')}Choose files</button><button class="primary" id="save-capture" type="submit">Save to today ${icon('plus')}</button></div></form>`;$('#choose-files').onclick=()=>$('#file-picker').click();$('#capture-form').onsubmit=async e=>{e.preventDefault();await saveText($('#paste').value)};bindCommon();$('#paste').focus()}
function captureError(message){if($('#capture-error')){$('#capture-error').hidden=false;$('#capture-error').textContent=message}feedback('failure',message)}
const fresh=(extra)=>{const d=new Date();return {id:crypto.randomUUID(),day:M.dayKey(d),capturedAt:d.toISOString(),zone:Intl.DateTimeFormat().resolvedOptions().timeZone,comment:'',reminder:'',...extra}};
async function commitCaptures(items){if(saving)return;saving=true;widget.dataset.state='saving';const btn=$('#save-capture');if(btn){btn.disabled=true;btn.textContent='Saving…'}const before=[...entries];try{await new Promise(r=>setTimeout(r,320));entries.push(...items);persist();await hydrateFiles();if($('#paste'))$('#paste').value='';if($('#capture-error'))$('#capture-error').hidden=true;if(screen==='daily'){day=today;filter='all';daily()}if(screen==='search')renderResults();feedback('success',items.length===1?'Saved to today.':`${items.length} captures saved to today.`,items[0]);return items}catch(err){entries=before;captureError(err.message);return []}finally{saving=false;if(btn){btn.disabled=false;btn.innerHTML='Save to today '+icon('plus')}}}
async function saveText(text){if(!text.trim()){captureError('There is nothing to save yet. Paste text or choose a file.');return []}const raw=text.trim(),lines=raw.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const parts=lines.length>1&&lines.every(x=>M.classify(x)==='link')?lines:[raw];return commitCaptures(parts.map(value=>{const kind=M.classify(value),host=kind==='link'?new URL(value).hostname:'';return fresh({kind,title:kind==='link'?host+new URL(value).pathname:value.split('\n')[0].slice(0,130),description:kind==='link'?'Preview unavailable. The original link is saved.':value.length>130?value.slice(130,350):'',original:value,source:host||'Text'})}))}
function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open('dabin-v2-files',1);req.onupgradeneeded=()=>req.result.createObjectStore('files');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(Error('This browser could not store the file.'))})}
async function storeFile(id,file){const db=await openDB();await new Promise((res,rej)=>{const tx=db.transaction('files','readwrite');tx.objectStore('files').put(file,id);tx.oncomplete=res;tx.onerror=()=>rej(Error('The file could not be saved. Browser storage may be full.'))});db.close()}
async function getFile(id){const db=await openDB();const blob=await new Promise((res,rej)=>{const r=db.transaction('files').objectStore('files').get(id);r.onsuccess=()=>res(r.result);r.onerror=rej});db.close();return blob}
async function saveFiles(files){if(saving)return;try{const items=[];for(const f of files){const e=fresh({kind:M.fileKind(f),title:f.name,description:`${f.type||'File'} · ${f.size<1024?f.size+' B':Math.round(f.size/1024)+' KB'}`,original:'',source:({image:'Image',video:'Video',pdf:'PDF',ai:'Illustrator',document:'Document',file:'File'})[M.fileKind(f)],fileName:f.name});await storeFile(e.id,f);e.fileId=e.id;items.push(e)}return await commitCaptures(items)}catch(err){captureError(err.message);return []}}
async function hydrateFiles(){for(const e of entries.filter(e=>e.fileId)){try{const f=await getFile(e.fileId);if(f&&!e.objectURL){e.objectURL=URL.createObjectURL(f);if(e.kind==='image')e.preview=e.objectURL}}catch{}}}
function detail(){const e=entryBy(P.get('id'))||(!P.has('id')?entries[0]:null);if(!e){panel.innerHTML=head('Capture')+empty('Capture not found.','Return to Daily to find your saved items.','<a class="secondary" href="daily.html">Open Daily</a>');bindCommon();return}const from=['daily','search','reminders'].includes(P.get('from'))?P.get('from'):'daily',back=url(from,from==='search'?{q:P.get('q')||'',filter:P.get('filter')||'all'}:{day:e.day,filter:P.get('filter')||'all'});panel.innerHTML=`<header class="panel-head"><a class="back" href="${back}">${icon('left')}${from==='search'?'Search':from==='reminders'?'Reminders':'Daily'}</a><button class="icon-button close-panel" aria-label="Close panel">${icon('close')}</button></header><div class="scroll detail-content"><div class="detail-hero">${e.kind==='video'&&e.objectURL?`<video controls src="${E(e.objectURL)}"></video>`:e.preview?`<img src="${E(e.preview)}" alt="${E(e.title)}">`:''}</div><p class="detail-caption">${E(fullDate(e.day))} · ${time(e)}</p><h1>${E(e.title)}</h1><p class="description">${E(e.kind==='text'?e.original:e.description)}</p><div class="original"><div class="original-source">${E(e.source)}${e.kind==='link'?`<br>${E(e.original)}`:''}</div><button class="secondary" id="open-original">${icon(e.kind==='text'?'copy':'open')}${e.kind==='text'?'Copy text':'Open original'}</button></div><form id="detail-form"><div class="field"><label class="form-label" for="comment">Comment <span>Optional</span></label><textarea id="comment" placeholder="A thought for later…" rows="3">${E(e.comment)}</textarea></div><div class="field"><label class="form-label" for="reminder">Reminder <span>Optional</span></label><input type="datetime-local" id="reminder" value="${E(e.reminder)}"><button type="button" class="text-button" id="clear-reminder">Clear reminder</button></div><p class="hint">Always kept on ${E(new Date(e.day+'T12:00:00').toLocaleDateString('en',{month:'long',day:'numeric'}))}.</p><div class="detail-save"><span class="status-text" id="detail-status" role="status"></span><button class="primary" type="submit">Save changes</button></div></form></div>`;
$('#open-original').onclick=async()=>{try{if(e.kind==='text'){await navigator.clipboard.writeText(e.original);notice('Text copied.')}else if(e.objectURL){const a=document.createElement('a');a.href=e.objectURL;a.download=e.fileName||e.title;a.click()}else if(safeOriginal(e.original)){window.open(e.original,'_blank','noopener,noreferrer')}else notice('The original file is not included in this sample.')}catch{notice('Clipboard access is unavailable. Select the text to copy it.')}};
$('#clear-reminder').onclick=()=>{$('#reminder').value='';$('#detail-status').textContent='Save to clear this reminder.'};
$('#detail-form').onsubmit=evt=>{evt.preventDefault();const previous=[...entries];entries=entries.map(x=>x.id===e.id?M.edit(x,$('#comment').value,$('#reminder').value):x);try{persist();$('#detail-status').textContent='Changes saved.'}catch(err){entries=previous;notice(err.message)}};bindCommon();if(P.get('focus'))setTimeout(()=>$('#'+(P.get('focus')==='reminder'?'reminder':'comment'))?.focus(),50)}
function bindCommon(){document.querySelectorAll('.close-panel').forEach(el=>el.onclick=()=>{panel.hidden=true;$('#robot').focus()});document.querySelectorAll('[data-filter]').forEach(el=>el.onclick=()=>{filter=el.dataset.filter;if(screen==='daily'){history.replaceState(null,'',url('daily',{day,filter}));daily()}else{search();history.replaceState(null,'',url('search',{q:query,filter}))}});document.querySelectorAll('img.thumb,.detail-hero img').forEach(img=>img.onerror=()=>{img.replaceWith(Object.assign(document.createElement('span'),{className:'thumb file-thumb',textContent:'Preview unavailable'}))})}
// Delay the click action until the double-click window has passed.
$('#robot').onclick=e=>{if(e.detail===0){nav('capture');return}clearTimeout(timer);if(e.detail===1)timer=setTimeout(()=>nav('capture'),480)};
$('#robot').ondblclick=()=>{clearTimeout(timer);nav('daily')};
$('#robot').onkeydown=e=>{if(e.key==='ArrowDown'){e.preventDefault();nav('daily')}};
$('#file-picker').onchange=async e=>{if(e.target.files.length)await saveFiles([...e.target.files]);e.target.value=''};
let dragDepth=0;
document.addEventListener('dragenter',e=>{e.preventDefault();dragDepth++;widget.dataset.state='drop';$('#widget-hint').textContent='Release to capture';panel.classList.add('dragging')});
document.addEventListener('dragover',e=>{e.preventDefault();if(e.dataTransfer)e.dataTransfer.dropEffect='copy'});
document.addEventListener('dragleave',()=>{if(--dragDepth<=0){widget.dataset.state='idle';panel.classList.remove('dragging')}});
document.addEventListener('drop',async e=>{e.preventDefault();dragDepth=0;panel.classList.remove('dragging');const dt=e.dataTransfer;if(dt.files.length)await saveFiles([...dt.files]);else{let value=dt.getData('text/uri-list').split('\n').filter(l=>!l.startsWith('#')).join('\n').trim()||dt.getData('text/plain');if(!value&&dt.getData('text/html')){const doc=new DOMParser().parseFromString(dt.getData('text/html'),'text/html');value=doc.querySelector('a')?.href||doc.body.textContent}if(value?.trim())await saveText(value);else captureError('Nothing readable was provided. Try copying the text or choosing the file.')}});
document.addEventListener('paste',async e=>{if(e.clipboardData.files.length){e.preventDefault();await saveFiles([...e.clipboardData.files])}else if(!e.target.matches('input,textarea')){e.preventDefault();const t=e.clipboardData.getData('text/plain');if(t)await saveText(t)}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){panel.hidden=true;$('#robot').focus()}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();nav('search')}if((e.metaKey||e.ctrlKey)&&e.shiftKey&&e.key.toLowerCase()==='d'){e.preventDefault();nav('daily')}});
// Move handle: pointer and keyboard. Persist only the widget's desktop position.
let start;
function position(x,y){x=Math.max(0,Math.min(innerWidth-58,x));y=Math.max(0,Math.min(innerHeight-78,y));widget.style.left=x+'px';widget.style.top=y+'px';widget.style.right='auto';try{sessionStorage.setItem('dabin:position',JSON.stringify({x,y}))}catch{}}
try{const p=JSON.parse(sessionStorage.getItem('dabin:position'));if(p&&!review)position(p.x,p.y)}catch{}
$('#grip').onpointerdown=e=>{const r=widget.getBoundingClientRect();start={x:e.clientX-r.x,y:e.clientY-r.y};e.currentTarget.setPointerCapture(e.pointerId)};
$('#grip').onpointermove=e=>{if(start)position(e.clientX-start.x,e.clientY-start.y)};$('#grip').onpointerup=()=>start=null;
$('#grip').onkeydown=e=>{const dirs={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]},d=dirs[e.key];if(d){e.preventDefault();const r=widget.getBoundingClientRect(),n=e.shiftKey?25:5;position(r.x+d[0]*n,r.y+d[1]*n)}};
if(P.get('appearance')==='dark')document.documentElement.dataset.appearance='dark';
await hydrateFiles();
({daily,search,capture,detail,reminders,rest:()=>panel.hidden=true})[screen]?.();
if(!storageOK)notice('Browser storage is unavailable. Captures cannot be saved here.');
if(review){const state=P.get('review');if(['drop','saving','success','failure'].includes(state))widget.dataset.state=state;if(state==='hover')widget.classList.add('review-hover');if(state==='success')notice('Saved to today.',entries[0]);if(state==='failure')notice('Nothing readable was provided. Try copying the text or choosing the file.');if(state==='empty'){day=M.shift(today,-7);daily()}if(state==='empty-filter'){day=M.shift(today,-1);filter='media';daily()}}
// Optional agent entrypoints use the same visible UI actions.
if(document.modelContext?.registerTool){const lifecycle=new AbortController();for(const tool of [{name:'search_captures',description:'Search saved captures across days with neighboring same-day context.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:input=>{if(typeof input.query!=='string')throw Error('query must be text');return M.search(entries,input.query).map(g=>({day:g.day,items:g.items.map(i=>({id:i.entry.id,title:i.entry.title,match:i.match}))}))}},{name:'save_text_capture',description:'Save text or a URL as a capture on today’s local calendar date.',inputSchema:{type:'object',properties:{text:{type:'string'}},required:['text'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async input=>{if(typeof input.text!=='string'||!input.text.trim())throw Error('Nonempty text is required');const saved=await saveText(input.text);return saved?.map(e=>({id:e.id,day:e.day}))}}]){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}}window.addEventListener('pagehide',()=>lifecycle.abort())}
window.DaBinApp={get entries(){return entries},saveText,saveFiles,search:M.search};
})();
