function attachHandlers(){
bindProjectSwitcher();
let robotClick;
$('#robot-intake')?.addEventListener('click',()=>{clearTimeout(robotClick);robotClick=setTimeout(()=>pasteCapture(),260)});
$('#robot-intake')?.addEventListener('dblclick',()=>{clearTimeout(robotClick);go('inbox')});
$('#quick-text')?.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();$('#quick-capture').requestSubmit()}});

$('#quick-capture')?.addEventListener('submit',e=>{e.preventDefault();const x=createCapture($('#quick-text').value);if(x){render();toast('Saved to Inbox');celebrate()}else if(!$('#quick-text').value.trim())toast('Add a thought, a link or a file first.',true)});
$('#quick-text')?.addEventListener('input',e=>{state.drafts.inbox={text:e.target.value};save()});
$('#scratchpad')?.addEventListener('input',e=>{const key=state.project==='all'?'unfiled':state.project;state.notes[key]={text:e.target.value,updated:TODAY};$('#note-status').textContent='Saving…';clearTimeout(notesTimer);notesTimer=setTimeout(()=>{const ok=save();if($('#note-status'))$('#note-status').innerHTML=ok?'Saved locally':'Not saved · <button data-action="retry-note">Retry</button>'},250)});
$('#search-form')?.addEventListener('submit',e=>{e.preventDefault();state.query=$('#search-input').value;save();searchResults()});
$('#search-input')?.addEventListener('input',e=>{state.query=e.target.value;save();searchResults()});
$('#nearby')?.addEventListener('change',e=>{state.nearby=e.target.checked;save();searchResults()});
$('#detail-form')?.addEventListener('input',detailDraft);
$('#detail-form')?.addEventListener('submit',e=>{e.preventDefault();let d=detailDraft();if(d.checklist?.some(x=>!x.text.trim()||x.text.length>500)){toast('Each checklist step needs 1–500 characters.',true);return}if(change(()=>{Object.assign(current(),d);delete state.drafts[currentId]})){toast('Changes saved');celebrate()}});
$('#new-form')?.addEventListener('input',e=>{let f=e.currentTarget;if(f.elements.planned)f.elements.planned.setCustomValidity('');state.drafts[PAGE]=Object.fromEntries(new FormData(f));save()});
$('#new-form')?.addEventListener('submit',e=>{e.preventDefault();let f=e.currentTarget,d=Object.fromEntries(new FormData(f));if(PAGE==='new-task'&&(Number(d.hours||0)*60+Number(d.minutes||0)>10080)){toast('Use a duration up to 168 hours.',true);return}if(d.scheduledTime&&!d.planned){f.elements.planned.setCustomValidity('Choose a day for this time.');f.elements.planned.reportValidity();return}let x=createCapture(d.text||d.title,PAGE==='new-task');if(!x)return;const ok=change(()=>{x.title=d.title.trim();x.planned=d.planned||null;x.effort=(Number(d.hours||0)*60+Number(d.minutes||0))||null;x.scheduledTime=d.scheduledTime||null;delete state.drafts[PAGE]},false);if(ok)go(x.task?'task-detail':'capture-detail','?id='+x.id)});
$('#reminder-form')?.addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget;let when;if(state.timerMode){let h=Number(f.elements.hours.value),m=Number(f.elements.minutes.value);if(h<0||h>99||m<0||m>59||h*60+m<=0){toast('Use 0–99 hours, 0–59 minutes, and a nonzero duration.',true);return}when=new Date(Date.now()+(h*60+m)*60000).toISOString()}else when=f.elements.when.value;if(!when||!Number.isFinite(new Date(when).getTime())){toast('Choose a valid date and time.',true);return}if(new Date(when)<=new Date()){toast('Choose a future reminder time.',true);return}if(change(()=>{current().reminder=when;if(state.timerMode)current().countdownEnd=when},false)){go(current().task?'task-detail':'capture-detail','?id='+currentId)}});
$('#file-input')?.addEventListener('change',e=>intakeFiles(e.target.files,pendingImportParent));
$('#backup-file')?.addEventListener('change',async e=>{try{const f=e.target.files[0];if(!f)return;const d=JSON.parse(await f.text());if(d.format!=='dabin-design-fixture-v1'||!Array.isArray(d.state?.items)||!Array.isArray(d.state?.projects)||!d.state?.notes)throw Error('This is not a DaBin design fixture backup. Native packages must be restored in DaBin.');if(Object.keys(state.drafts).length)throw Error('Save or discard unfinished drafts before restoring.');const p=d.state;for(const x of p.items){if(!x.id||!x.title||!x.date||!x.type)throw Error('The backup contains an invalid capture.');if(item(x.id)&&JSON.stringify(item(x.id))!==JSON.stringify(x))throw Error('Conflicting capture: '+x.title+'. Nothing was overwritten.')}for(const [k,n]of Object.entries(p.notes)){if(state.notes[k]&&state.notes[k].text!==n.text)throw Error('Conflicting scratchpad: '+k+'. Nothing was overwritten.')}window.pendingRestore=p;openDialog('Review additive restore',`<p>${p.items.filter(x=>!item(x.id)).length} new captures. Identical records are skipped. No conflicts were found in the fixture.</p>`,button('Cancel','close-dialog')+button('Restore fixture','backup-apply','primary'))}catch(err){toast(err.message,true)}});
$('#dialog')?.addEventListener('click',e=>{if(e.target===$('#dialog'))closeDialog()});$('#dialog')?.addEventListener('cancel',()=>setTimeout(()=>lastFocus?.focus(),0));
const app=$('#app');app?.addEventListener('dragover',e=>{e.preventDefault();app.classList.add('drag-over')});app?.addEventListener('dragleave',e=>{if(!app.contains(e.relatedTarget))app.classList.remove('drag-over')});app?.addEventListener('drop',e=>{e.preventDefault();app.classList.remove('drag-over');let parent=PAGE==='task-detail'?currentId:null;if(e.dataTransfer.files.length)intakeFiles(e.dataTransfer.files,parent);else{let t=e.dataTransfer.getData('text/plain');if(t){let x=createCapture(t);if(x&&parent)change(()=>{x.parent=parent;current().attachments??=[];current().attachments.push(x.id)});else render();toast('Capture saved');celebrate()}else toast('No readable content. Try importing the original file.',true)}});
let handle=$('#resize-handle');handle?.addEventListener('pointerdown',e=>{e.preventDefault();const frame=$('#frame'),rect=frame.getBoundingClientRect(),start={x:e.clientX,y:e.clientY,...{left:rect.left,top:rect.top,width:rect.width,height:rect.height}};handle.setPointerCapture(e.pointerId);handle.onpointermove=m=>{const viewport=viewportRect();setFrameRect(frame,fitWindowRect({left:start.left,top:start.top,width:Math.max(Math.min(400,viewport.width),Math.min(viewport.left+viewport.width-start.left,start.width+m.clientX-start.x)),height:Math.max(Math.min(480,viewport.height),Math.min(viewport.top+viewport.height-start.top,start.height+m.clientY-start.y))},viewport));positionProjectSwitcher()};handle.onpointerup=handle.onpointercancel=()=>handle.onpointermove=null});
$('#move-handle')?.addEventListener('pointerdown',e=>{e.preventDefault();const el=e.currentTarget,frame=$('#frame'),rect=frame.getBoundingClientRect(),start={x:e.clientX,y:e.clientY,left:rect.left,top:rect.top,width:rect.width,height:rect.height};el.setPointerCapture(e.pointerId);el.onpointermove=m=>{setFrameRect(frame,fitWindowRect({left:start.left+m.clientX-start.x,top:start.top+m.clientY-start.y,width:start.width,height:start.height},viewportRect()));positionProjectSwitcher()};el.onpointerup=el.onpointercancel=()=>el.onpointermove=null});
}
document.addEventListener('submit',submitTaskTiming);
setInterval(updateTaskTimers,1000);
document.addEventListener('visibilitychange',()=>{if(!document.hidden)updateTaskTimers()});
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]');if(a){e.preventDefault();if(a.dataset.action==='retry-note'){const ok=save();$('#note-status').textContent=ok?'Saved locally':'Not saved. Copy your notes to retain them.';return}handleAction(a).catch(err=>toast('Action could not finish: '+err.message,true))}const link=e.target.closest('a[href]');if(link&&!link.target)saveContext()});
document.addEventListener('change',e=>{const el=e.target;if(el.dataset.change){const k=el.dataset.change;if(k==='project'&&el.value==='__new'){askName('Create a project','','new-project-save');return}change(()=>state[k]=el.value)}if(el.dataset.setting){const k=el.dataset.setting;change(()=>state.settings[k]=k==='opacity'?Number(el.value):el.value)}});
document.addEventListener('paste',e=>{if(e.target.matches('input,textarea,[contenteditable=true]'))return;if(!['inbox','activity','task-detail','robot','shelf'].includes(PAGE))return;e.preventDefault();if(e.clipboardData.files.length){intakeFiles(e.clipboardData.files,PAGE==='task-detail'?currentId:null);return}const text=e.clipboardData.getData('text/plain');if(text){let x=createCapture(text);if(x&&PAGE==='task-detail')change(()=>{x.parent=currentId;x.inbox=false;current().attachments??=[];current().attachments.push(x.id)});else if(x)render();if(x){toast('Capture saved');celebrate()}}});
document.addEventListener('keydown',e=>{const edit=e.target.matches('input,textarea,[contenteditable=true]');if(e.metaKey&&e.key.toLowerCase()==='k'){e.preventDefault();state.scope='All';go('search')}else if(e.metaKey&&e.key===','){e.preventDefault();go('settings')}else if(e.metaKey&&e.shiftKey&&e.key.toLowerCase()==='d'){e.preventDefault();go('today')}else if(e.metaKey&&e.key.toLowerCase()==='s'&&$('#detail-form')){e.preventDefault();$('#detail-form').requestSubmit()}else if(e.metaKey&&e.key==='Enter'&&$('#new-form')){e.preventDefault();$('#new-form').requestSubmit()}else if(e.key==='Escape'&&!$('#dialog')?.open&&!edit){if(['capture-detail','task-detail','search','reminder'].includes(PAGE))back();else handleAction({dataset:{action:'hide'}})}});
window.addEventListener('pagehide',()=>{clearTimeout(notesTimer);save();saveContext()});
/* Minimal store-only ZIP writer: no external library, complete shelf independent of filters. */
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#project-switcher')?.matches(':popover-open')){e.preventDefault();e.stopImmediatePropagation();$('#project-switcher').hidePopover();($$('[data-action="project-picker"]')[projectSwitcherTrigger]||$('.project-heading'))?.focus()}},true);
window.addEventListener('resize',()=>{keepFrameInViewport();positionProjectSwitcher()});
window.visualViewport?.addEventListener('resize',()=>{keepFrameInViewport();positionProjectSwitcher()});
window.visualViewport?.addEventListener('scroll',positionProjectSwitcher);
document.addEventListener('scroll',positionProjectSwitcher,true);

function crc32(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0}
async function exportShelf(){const xs=projectItems().filter(x=>x.shelf),enc=new TextEncoder();if(!xs.length){toast('This project shelf is empty.',true);return}try{let parts=[],central=[],offset=0,used=new Set();for(const x of xs){let filename=x.filename||x.title+'.txt',bytes;if(x.data){bytes=new Uint8Array(await(await fetch(x.data)).arrayBuffer())}else if(x.image||x.url&&x.url.startsWith(ASSETS)){const r=await fetch(x.image||x.url);if(!r.ok)throw Error('Missing managed file: '+x.title);bytes=new Uint8Array(await r.arrayBuffer())}else bytes=enc.encode(x.text||x.url||x.title);filename=filename.replace(/[\/\\:*?"<>|]/g,'_');if(used.has(filename))filename=x.id+'-'+filename;used.add(filename);let name=enc.encode(filename),crc=crc32(bytes),head=new Uint8Array(30+name.length),v=new DataView(head.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint32(14,crc,true);v.setUint32(18,bytes.length,true);v.setUint32(22,bytes.length,true);v.setUint16(26,name.length,true);head.set(name,30);parts.push(head,bytes);let dir=new Uint8Array(46+name.length),d=new DataView(dir.buffer);d.setUint32(0,0x02014b50,true);d.setUint16(4,20,true);d.setUint16(6,20,true);d.setUint16(8,0x800,true);d.setUint32(16,crc,true);d.setUint32(20,bytes.length,true);d.setUint32(24,bytes.length,true);d.setUint16(28,name.length,true);d.setUint32(42,offset,true);dir.set(name,46);central.push(dir);offset+=head.length+bytes.length}const size=central.reduce((s,x)=>s+x.length,0),end=new Uint8Array(22),v=new DataView(end.buffer);v.setUint32(0,0x06054b50,true);v.setUint16(8,xs.length,true);v.setUint16(10,xs.length,true);v.setUint32(12,size,true);v.setUint32(16,offset,true);let blob=new Blob([...parts,...central,end],{type:'application/zip'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='DaBin-Shelf-'+(state.project==='all'?'All-projects':state.project.replace(/[\/\\]/g,'-'))+'.zip';a.click();setTimeout(()=>URL.revokeObjectURL(u),3000);toast('Complete project shelf ZIP prepared · '+xs.length+' items')}catch(err){toast('Shelf export failed: '+err.message,true)}}

render();try{const ctx=JSON.parse(sessionStorage.getItem('dabin:context:'+PAGE));if(ctx&&$('.main'))$('.main').scrollTop=ctx.scroll}catch{}
