/* Event delegation and explicit save boundaries. Native-only controls identify simulations. */
let pendingImportParent=null,notesTimer;
const menuEntry=(label,action,id='',icon='')=>`<button data-action="${action}" data-id="${esc(id)}">${icon?ic(icon):''}${label}</button>`;
const localSpecs={
'file-location':['Saved file location','The native detail displays the actual managed destination, with Copy saved path, Reveal file and Open folder. Original source location is shown only when supplied. A missing managed file produces a recoverable error; it never points at a guessed path. The browser fixture has no native archive path.'],
'index-status':['Local recognized text','Native states: waiting → indexing → text available, no text found, or failed. Retry processes the same managed original locally with Vision/PDFKit. Copy text remains disabled until text exists. Large documents retain explicit source limits; no remote AI is used.'],
'notification':['Notification delivery','Native states: not requested → request on first reminder → allowed or denied. Denied shows Open System Settings and Retry status; a scheduling failure retains the reminder with an error. Completion cancels the active notification. Browser fixture times persist, but no system notification is scheduled.'],
'choose-folder':['Choose screenshot folder','The native folder picker stores a security-scoped bookmark. Cancel preserves the old folder; authorization failure exposes Choose again. Enabling starts a fresh baseline and never imports old images. Clipboard capture remains independent. No folder access is granted by this browser simulation.'],
'capture-status':['Capture source status','Each source has Off, Active, Paused, Excluded, Permission needed/revoked and Failed states. Pause immediately stops new intake, retains existing records, and resumes with a fresh baseline. Only persisted successful actions may trigger robot confirmation.'],
'shortcut-status':['Global shortcut registration','Native choices are the two displayed combinations or Disabled. A registration conflict shows the conflicting combination, offers the alternate, and retains the previous working registration. DaBin does not monitor general typing. Browser keyboard shortcuts operate only while this document is focused.'],
'archive':['Local archive','Open the native archive folder: year → numbered named month → numbered named day with weekday → unique capture folder. Core Data metadata is authoritative. Managed imports are copies; source originals are unchanged. Missing folder or access errors offer Retry without creating an alternate archive.'],
'rebuild-index':['Rebuild local text index','Native sequence: confirm scope → queued/progress → complete with indexed/failed counts. Retry failed originals individually. Save and capture remain available with bounded indexing concurrency. Cancel stops queued work and retains existing searchable text.'],
'updates':['Get updates · direct build','Installed baseline: 0.4.2 (53). A user-initiated check may return current, available, unavailable or failed. Available releases show release details before download; verify the package, back up, then install. Verification or backup failure blocks installation. No release availability has been checked here.'],
'store-updates':['Updates · App Store build','Show installed version and “Managed by the App Store”. Open the App Store application page only when its configured destination is available. The direct downloader and update helper are excluded from this build. This prototype does not assert App Store availability.'],
'privacy':['Private by design','Native DaBin stores captures and recognized text locally. No account, analytics, ads, cloud sync or remote OCR. Manual link previews and explicit update checks are disclosed network requests. Source attribution and sensitive-app exclusion are best effort. DaBin does not automatically observe where content is later pasted. The content trail stores destinations you explicitly record; copying alone never records a paste.'],
'support':['Support','Native Settings opens the configured support and privacy destinations from PrivacyInformation.swift. No support message is sent from this prototype. Include version, reproduction steps and a redacted diagnostic description; never attach live clipboard content automatically.'],
'export-spec':['Native export states','Copy and Save Text use the identical UTF-8 payload. Save panel cancellation is neutral. Clipboard failure retains the existing clipboard; disk failure retains the payload and offers Retry or Copy. An empty scope disables both actions. Exports ignore type filters and carried-task duplicates.'],
'backup-states':['Native verified backup','Idle → local destination picker → busy progress → checksum verification → verified success. Cancel leaves no accepted partial package. Unavailable destination, interrupted write or corrupt manifest shows a specific error and preserves the working archive. Pending unsaved edits must save before backup starts.'],
'backup-conflicts':['Native additive restore','Read and verify every entry before mutation. Identical records are skipped; new records are added. Conflicting capture or scratchpad content blocks restore for review without overwriting authored work. A corrupt or unavailable package cannot be partially applied. The recovery journal retains a stable pre-operation state.'],
'placement-states':['Native robot placement','Resting is hidden. Entering the chosen corner or compatible island reveals a stable intake target on the interacted display. A display change clamps to its safe area; missing island or external display falls back to top right. Opening wins over capture animations. Decorative parts never intercept content clicks, change Spaces or steal focus.']};
function menu(title,html){openDialog(title,'<div class="menu-list">'+html+'</div>')}
function detailDraft(){const f=$('#detail-form'),x=current();if(!f||!x)return;const v={title:f.elements.title.value,comment:f.elements.comment.value,project:f.elements.project.value||null,pinned:f.elements.pinned.checked};if(f.elements.planned){Object.assign(v,{planned:f.elements.planned.value||null,scheduledTime:f.elements.scheduledTime?.value||null,priority:f.elements.priority.value,effort:f.elements.effort.value?Number(f.elements.effort.value):null,deadline:f.elements.deadline.value||null,repeat:f.elements.repeat.value,checklist:$$('[data-step]',f).map(n=>({text:n.value,done:$('[data-check="'+n.dataset.step+'"]',f).checked}))})}state.drafts[x.id]=v;save();if($('#task-save-state'))$('#task-save-state').textContent='Unsaved changes';return v}
function askName(title,value,action,id=''){openDialog(title,`<label class="field">Name<input id="name-value" value="${esc(value)}" required maxlength="180"></label>`,button('Cancel','close-dialog')+button('Save',action,'primary',id))}
async function intakeFiles(files,parent=null){if(busy)return;const list=Array.from(files);if(!list.length)return;busy=true;toast('Saving files…');const added=[];try{for(const f of list){if(f.size>8*1024*1024)throw Error('This browser fixture accepts files up to 8 MB. Native file intake is specified separately.');const data=await new Promise((res,rej)=>{let r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(Error('Could not read '+f.name));r.readAsDataURL(f)});const isImage=f.type.startsWith('image/'),type=isImage?'Media':f.type.startsWith('video/')?'Media':'Files';added.push({id:'file-'+crypto.randomUUID(),title:f.name,filename:f.name,type,text:f.type.startsWith('text/')?await f.text():'',image:isImage?data:undefined,data,mime:f.type,date:TODAY,time:new Date().toTimeString().slice(0,5),project:state.project==='all'||state.project==='unfiled'?null:state.project,inbox:!parent,parent,origin:'manual',shelf:PAGE==='shelf'})}const ok=change(()=>{state.items.unshift(...added);if(parent){item(parent).attachments??=[];item(parent).attachments.push(...added.map(x=>x.id))}else if(added.length>1){const b={id:'batch-'+Date.now(),title:added.length+' files, kept together',type:'Files',date:TODAY,time:new Date().toTimeString().slice(0,5),project:added[0].project,inbox:true,members:added.map(x=>x.id),origin:'manual'};added.forEach(x=>x.inbox=false);state.items.unshift(b)}});if(ok){toast(added.length+' file'+(added.length>1?'s':'')+' saved');celebrate()}}catch(e){toast(e.message,true)}finally{busy=false}}
async function pasteCapture(parent=null){try{const t=await navigator.clipboard.readText();if(!t.trim()){toast('No readable text. Paste into the capture field or import a file.',true);return}const x=createCapture(t);if(x&&parent)change(()=>{x.parent=parent;x.inbox=false;item(parent).attachments??=[];item(parent).attachments.push(x.id)});else render();if(x){toast('Capture saved');celebrate()}}catch{openDialog('Paste into DaBin','<p>Clipboard access needs a user gesture or permission. Paste your content here to save it.</p><textarea id="manual-paste" rows="5" placeholder="Paste text or a link…"></textarea>',button('Cancel','close-dialog')+button('Save capture','manual-paste-save','primary',parent||''))}}
async function handleAction(a){const act=a.dataset.action,id=a.dataset.id||currentId,val=a.dataset.value;if(handleTrailAction(a))return;if(await handleTaskAction(a))return;if(act==='close-dialog'){closeDialog();return}if(localSpecs[act]){native(...localSpecs[act]);return}switch(act){
case 'add':menu('Add to DaBin',menuEntry('Paste clipboard','paste','','copy')+'<a href="new-note.html">'+ic('note')+'New note</a>'+menuEntry('Import files','import','','clip')+'<a href="new-task.html">'+ic('task')+'New task</a>');break;
case 'paste':if($('#dialog').open)closeDialog();await pasteCapture();break;
case 'manual-paste-save':{const t=$('#manual-paste').value,x=createCapture(t);if(!x){toast('Add some text first.',true);break}if(a.dataset.id)change(()=>{x.parent=a.dataset.id;x.inbox=false;item(a.dataset.id).attachments??=[];item(a.dataset.id).attachments.push(x.id)},false);closeDialog();render();toast('Capture saved');celebrate();break}
case 'import':case 'attach-import':pendingImportParent=act==='attach-import'?id:null;if($('#dialog').open)closeDialog();$('#file-input').click();break;
case 'search':state.scope='All';go('search');break;
case 'settings':go('settings');break;
case 'back':back();break;
case 'parent':go('task-detail','?id='+id);break;
case 'expand':toggleFrameExpansion();break;
case 'hide':saveContext();document.body.innerHTML=`<div class="hidden-state"><div class="robot-entry"><img src="${ASSETS}original-robot.svg" alt="DaBin"><p class="meta">Window hidden · browser simulation</p><button class="btn" id="reopen">Open DaBin</button><a class="small-link" href="index.html">Back to design handoff</a></div></div>`;$('#reopen').onclick=render;break;
case 'quit':native('Quit DaBin','The native command saves recoverable drafts and terminates all capture services, timers and windows without waiting for animation. Browser documents cannot terminate the native app; close this tab to end this fixture session.');break;
case 'filter':change(()=>state.filter=val);break;
case 'today-tab':change(()=>state.todayTab=val);break;
case 'clipboard-tab':change(()=>state.clipboardTab=val);break;
case 'copy':{const x=item(id);if(x.members||x.type==='Files'&&!x.text||x.image){native('Copy original content','The native clipboard action copies '+(x.members?'the complete group of original file payloads atomically':'the saved original payload')+'. If any member is unavailable, retain the previous clipboard and report failure. Browser image/file clipboard equivalence is not claimed.');break}await copyText(x.text||x.url||x.title);break}
case 'copy-plain':await copyText(item(id).text||item(id).indexed||item(id).url||'');break;
case 'copy-index':await copyText(item(id).indexed||'');break;
case 'keep':if(change(()=>{item(id).inbox=false;item(id).kept=true})){toast('Kept in Workspace');celebrate()}break;
case 'card-menu':{let x=item(id);menu(x.title,`<a href="${taskRoute(x)}">${ic('external')} Open detail</a>`+menuEntry('Copy as plain text','copy-plain',id,'copy')+menuEntry(x.task?'Open work plan':'Turn into task','convert',id,'task')+menuEntry('Plan for Today','plan-today',id,'sun')+menuEntry('File to project','file-project',id,'folder')+menuEntry(x.pinned?'Unpin':'Pin','pin',id,'pin')+menuEntry(x.shelf?'Remove from shelf; keep capture':'Keep on shelf','shelf-toggle',id,'shelf')+menuEntry(x.snippet?'Rename snippet':'Name snippet','snippet',id,'text')+(x.snippet?menuEntry('Remove snippet alias','remove-snippet',id):'')+menuEntry(x.minimized?'Expand preview':'Minimize preview','minimize',id,'minus')+menuEntry('Move to Recently Deleted','trash-confirm',id,'trash'));break}
case 'task-menu':menu('Plan task',menuEntry('Work on Today','plan-today',id,'sun')+menuEntry('Move to Tomorrow','plan-tomorrow',id,'calendar')+menuEntry('Remove planned workday','unplan',id,'inbox')+menuEntry('Move to Recently Deleted','trash-confirm',id,'trash')+menuEntry('Move earlier','order-up',id)+menuEntry('Move later','order-down',id)+`<a href="task-detail.html?id=${id}">${ic('task')} Work plan & details</a>`);break;
case 'plan-today':case 'plan-tomorrow':case 'unplan':change(()=>{let x=item(id);x.task=true;x.planned=act==='unplan'?null:act==='plan-today'?TODAY:dayAdd(TODAY,1);x.checklist??=[];x.attachments??=[]});toast(act==='unplan'?'Workday cleared':'Task planned');break;
case 'order-up':case 'order-down':{let xs=projectItems().filter(x=>x.task&&!x.completed&&x.planned===item(id).planned).sort((a,b)=>(a.order??99)-(b.order??99));const i=xs.findIndex(x=>x.id===id),j=Math.max(0,Math.min(xs.length-1,i+(act==='order-up'?-1:1)));[xs[i],xs[j]]=[xs[j],xs[i]];change(()=>xs.forEach((x,i)=>x.order=i));break}
case 'convert':convertCapture(id);break;
case 'pin':change(()=>item(id).pinned=!item(id).pinned);break;
case 'minimize':change(()=>item(id).minimized=!item(id).minimized);break;
case 'shelf-toggle':{let was=item(id).shelf;change(()=>item(id).shelf=!was);toast(was?'Removed from shelf. Capture kept in Library.':'Added to shelf');break}
case 'file-project':openDialog('File to project',`<label class="field">Project<select id="file-project"><option value="">Unfiled</option>${state.projects.map(p=>'<option '+(item(id).project===p?'selected':'')+'>'+esc(p)+'</option>').join('')}</select></label>`,button('Cancel','close-dialog')+button('Save project','file-project-save','primary',id));break;
case 'file-project-save':{let p=$('#file-project').value;change(()=>item(id).project=p||null);toast('Project saved');break}
case 'snippet':askName('Name reusable snippet',item(id).snippet||'','save-snippet',id);break;
case 'save-snippet':{let n=$('#name-value').value.trim();if(!n){toast('A snippet needs a name.',true);break}change(()=>item(id).snippet=n);toast('Snippet alias saved. Original content retained.');break}
case 'remove-snippet':change(()=>delete item(id).snippet);toast('Alias removed. Capture kept.');break;
case 'new-project-save':{let n=$('#name-value').value.trim();if(!n||state.projects.includes(n)){toast('Use a new, nonempty project name.',true);break}change(()=>{state.projects.push(n);state.project=n});break}
case 'complete':toggleComplete(id);break;
case 'trash-confirm':openDialog('Move to Recently Deleted?',`<p>${esc(item(id).title)}${item(id).task?' and its attached captures':''} can be restored. Original external files stay untouched.</p>`,button('Cancel','close-dialog')+button('Move to Recently Deleted','trash','danger',id));break;
case 'trash':trash(id);if(['task-detail','capture-detail'].includes(PAGE))go('recently-deleted');break;
case 'undo':if(state.lastDeleted)restore(state.lastDeleted);break;
case 'restore':restore(id);break;
case 'permanent':openDialog('Permanently delete this capture?',`<p>This removes the saved record and its managed copies from this browser fixture. It cannot be undone. External originals are untouched.</p>`,button('Keep capture','close-dialog')+button('Delete permanently','permanent-confirm','danger',id));break;
case 'permanent-confirm':change(()=>{const family=new Set([id,...(item(id).attachments||[])]);state.items=state.items.filter(x=>!family.has(x.id));state.items.forEach(x=>{if(x.members)x.members=x.members.filter(i=>!family.has(i))})});toast('Permanently deleted');break;
case 'add-step':{let d=detailDraft();if(d.checklist.length>=100){toast('A checklist can contain up to 100 steps.',true);break}d.checklist.push({text:'',done:false});save();render();$$('[data-step]').at(-1)?.focus();break}
case 'remove-step':{let d=detailDraft();d.checklist.splice(Number(val),1);save();render();break}
case 'attach-existing':case 'shelf-add':{let candidates=alive().filter(x=>!x.task&&!x.parent&&(!current()?.attachments?.includes(x.id)));menu(act==='shelf-add'?'Add an existing capture':'Attach saved capture',candidates.map(x=>menuEntry(esc(x.title),act==='shelf-add'?'shelf-existing-save':'attach-existing-save',x.id)).join(''));break}
case 'shelf-existing-save':change(()=>item(id).shelf=true);toast('Added to shelf');break;
case 'attach-existing-save':change(()=>{current().attachments??=[];current().attachments.push(id);item(id).parent=currentId});toast('Capture attached');break;
case 'attach-paste':await pasteCapture(id);break;
case 'note-convert':case 'note-task':{let key=state.project==='all'?'unfiled':state.project,t=state.notes[key]?.text;if(!t?.trim()){toast('Write something first.',true);break}let x=createCapture(t,act==='note-task');if(x){render();toast(act==='note-task'?'Task created. Scratchpad retained.':'Note saved. Scratchpad retained.')}break}
case 'discard-draft':openDialog('Discard this draft?','<p>The unsaved draft will be removed. Saved captures are unaffected.</p>',button('Keep writing','close-dialog')+button('Discard','discard-confirm','danger'));break;
case 'discard-confirm':delete state.drafts[PAGE];save();go('inbox');break;
case 'reminder-mode':change(()=>state.timerMode=val==='timer');break;
case 'remove-reminder':case 'reminder-done':change(()=>{delete item(id).reminder;delete item(id).countdownEnd});toast('Reminder cleared');break;
case 'reminder-tomorrow':change(()=>item(id).reminder=dayAdd(TODAY,1)+'T09:00:00');toast('Reminder moved to tomorrow');break;
case 'date-prev':case 'date-next':change(()=>state.date=dayAdd(state.date,(act==='date-prev'?-1:1)*(PAGE==='weekly'?7:1)));break;
case 'date-today':change(()=>state.date=TODAY);break;
case 'open-day':state.date=val;go('activity');break;
case 'scope-search':state.scope=PAGE==='weekly'?'Week':'Day';go('search');break;
case 'clear-refinements':change(()=>{state.filter='All';state.project='all';state.source='all';state.origin='all';state.dateFilter='all';state.pinned=false});break;
case 'all-dates':change(()=>state.scope='All');break;
case 'refine':openDialog('Refine this view',`<div class="stack"><label class="field">Source app<select id="ref-source"><option value="all">All apps</option>${['Mail','Notes','Finder','Safari'].map(v=>'<option '+(state.source===v?'selected':'')+'>'+v+'</option>').join('')}</select></label><label class="field">Date<select id="ref-date">${[['all','All dates'],['Today','Today'],['Yesterday','Yesterday']].map(([v,l])=>'<option value="'+v+'" '+(state.dateFilter===v?'selected':'')+'>'+l+'</option>').join('')}</select></label><label class="field">Origin<select id="ref-origin">${[['all','All origins'],['manual','Manual captures'],['clipboard','Automatic clipboard']].map(([v,l])=>'<option value="'+v+'" '+(state.origin===v?'selected':'')+'>'+l+'</option>').join('')}</select></label><label class="row"><input type="checkbox" id="ref-pinned" ${state.pinned?'checked':''}>Pinned only</label></div>`,button('Clear','clear-refinements')+button('Apply','refine-save','primary'));break;
case 'refine-save':{const source=$('#ref-source').value,date=$('#ref-date').value,origin=$('#ref-origin').value,pinned=$('#ref-pinned').checked;change(()=>{state.source=source;state.dateFilter=date;state.origin=origin;state.pinned=pinned});break}
case 'export-copy':await copyText($('#export-content').value);break;
case 'export-file':download(val==='Week'?`DaBin-${dayAdd(state.date,-6)}-to-${state.date}.txt`:`DaBin-${state.date}.txt`,$('#export-content').value);toast('Text file prepared');break;
case 'shelf-export':exportShelf();break;
case 'auto-menu':menu(autoLabel(),'<a href="settings.html">'+ic('gear')+'Capture settings</a>'+((state.settings.clipboard||state.settings.screenshots)?menuEntry(state.settings.paused?'Resume new captures':'Pause new captures','pause','','pause'):'')+menuEntry('Source status & privacy','capture-status','','shield'));break;
case 'pause':change(()=>state.settings.paused=!state.settings.paused);toast(state.settings.paused?'New capture paused; existing captures kept.':'Resumed with a fresh baseline. Native monitoring remains simulated.');break;
case 'setting-toggle':change(()=>state.settings[val]=!state.settings[val]);if(['clipboard','screenshots'].includes(val)&&state.settings[val])toast('Preference saved. Native source monitoring is simulated in this browser.');break;
case 'accent':change(()=>state.settings.accent=val||a.dataset.id);break;
case 'solid':change(()=>state.settings.opacity=100);break;
case 'exclusions':openDialog('Excluded apps',`<p>Best-effort detection. DaBin always excludes itself.</p><div class="stack">${state.settings.exclusions.map(n=>'<div class="row between"><span>'+esc(n)+'</span>'+(n==='DaBin'?'<span class="tag">Always excluded</span>':button('Remove','exclude-remove','',''+n))+'</div>').join('')}</div><div class="row" style="margin-top:15px"><input id="exclude-name" placeholder="Application name" aria-label="Excluded application"><button class="btn" data-action="exclude-add">Add</button></div>`,button('Restore defaults','exclude-reset')+button('Done','close-dialog'));break;
case 'exclude-add':{let n=$('#exclude-name').value.trim();if(n&&!state.settings.exclusions.includes(n))change(()=>state.settings.exclusions.push(n));toast('Exclusion saved');break}
case 'exclude-remove':if(a.dataset.id!=='DaBin')change(()=>state.settings.exclusions=state.settings.exclusions.filter(x=>x!==a.dataset.id));break;
case 'exclude-reset':change(()=>state.settings.exclusions=['DaBin','1Password','Keychain Access']);break;
case 'clear-history':{let xs=retentionCandidates();openDialog('Clear unfiled automatic copies?',`<p>${xs.length} eligible copies will move to Recently Deleted. Tasks, attachments, reminders, projects, pins, snippets, shelf and kept work are protected.</p>`,button('Cancel','close-dialog')+button('Move '+xs.length+' copies','clear-history-confirm','danger'));break}
case 'clear-history-confirm':change(()=>retentionCandidates().forEach(x=>x.deleted=new Date().toISOString()));toast('Eligible copies moved to Recently Deleted');break;
case 'backup-export':download('DaBin-design-fixture.json',JSON.stringify({format:'dabin-design-fixture-v1',state},null,2),'application/json');toast('Fixture backup prepared. Native backup remains a separate workflow.');break;
case 'backup-import':$('#backup-file').click();break;
case 'backup-apply':if(window.pendingRestore){change(()=>{const p=window.pendingRestore;state.items.push(...p.items.filter(x=>!item(x.id)));state.projects=[...new Set([...state.projects,...p.projects])];Object.assign(state.notes,p.notes)});window.pendingRestore=null;toast('Fixture restored additively')}break;
case 'robot-more':menu('DaBin',menuEntry('Motion preview','robot-study','','play')+menuEntry('Hide robot','robot-hide','','minus')+menuEntry('Reveal robot','robot-reveal','','sun')+menuEntry('Menu bar','status-menu')+menuEntry('Application menu','app-menu')+menuEntry('Placement','placement-states'));break;
case 'robot-study':openDialog('Motion preview',`<p>Preview only · no capture is saved.</p><div class="stack"><label class="field">Reaction<select id="reaction">${reactions.map((r,i)=>'<option value="'+i+'">'+r+'</option>').join('')}</select></label><label class="field">Capture count<input type="number" id="burst" min="1" max="99" value="1"></label><a class="small-link" href="open-design-v3/specs/ROBOT_MOTION.md">Motion specification</a></div>`,button('Shuffle','robot-shuffle')+button('Play','robot-play','primary'));break;
case 'robot-reveal':$('#motion-robot').style.opacity=1;$('#robot-state').textContent='Ready to capture';break;
case 'robot-hide':$('#motion-robot').style.opacity=0;$('#robot-state').textContent='Robot hidden';break;
case 'robot-play':playRobot(Number($('#reaction').value));break;
case 'robot-shuffle':{const previous=window.lastReactions||[],choices=reactions.map((_,i)=>i).filter(i=>!previous.includes(i)),i=choices[Math.floor(Math.random()*choices.length)];$('#reaction').value=i;window.lastReactions=[i,...previous].slice(0,3);playRobot(i);break}
case 'status-menu':menu('Menu bar · native simulation','<a href="inbox.html">Open DaBin</a>'+menuEntry(autoLabel(),'capture-status')+menuEntry('Pause / Resume','pause')+'<a href="settings.html">Settings… <kbd>⌘ ,</kbd></a>'+menuEntry('Quit DaBin','quit'));break;
case 'app-menu':menu('Application menu · native simulation',menuEntry('About DaBin 0.4.2 (53)','updates')+menuEntry('Get updates…','updates')+'<a href="inbox.html">Open DaBin <kbd>⌘ O</kbd></a>'+'<a href="robot.html">Focus robot for paste <kbd>⌘ ⇧ V</kbd></a>'+'<a href="search.html">Search <kbd>⌘ K</kbd></a>'+menuEntry(autoLabel(),'capture-status')+'<a href="settings.html">Settings <kbd>⌘ ,</kbd></a>'+menuEntry('Hide DaBin','hide')+menuEntry('Quit DaBin','quit'));break;
}}
function retentionCandidates(){return alive().filter(x=>x.auto&&!x.task&&!x.parent&&!x.reminder&&!x.project&&!x.pinned&&!x.snippet&&!x.shelf&&!x.inbox&&!x.kept&&!state.items.some(t=>t.attachments?.includes(x.id)))}
function playRobot(i){const stage=$('#robot-stage'),r=$('#motion-robot'),count=Math.max(1,Math.min(99,Number($('#burst')?.value)||1));if(!stage||!r)return;if($('#dialog')?.open)closeDialog();stage.classList.remove('play');void stage.offsetWidth;r.style.opacity=1;$('#capture-token').textContent=count;$('#robot-state').textContent='Motion preview · '+reactions[i];if(state.settings.reduceMotion||state.settings.quiet){toast('Static saved confirmation · '+count+' actions');return}stage.classList.add('play');const k=[[[0,0,1],[0,2,1.03],[0,0,1]],[[0,0,1],[-9,0,1.1],[5,-8,.98],[0,0,1]],[[0,0,1],[0,-4,.9],[0,2,1.1],[0,0,1]],[[0,0,1],[-5,2,.99],[5,2,.99],[-5,2,.99],[0,0,1]],[[0,0,1],[-7,-5,1],[6,-10,1],[0,0,1]],[[0,0,1],[0,5,1.17],[0,-4,.94],[0,0,1]],[[0,0,1],[-10,0,1],[10,0,1],[0,0,1]],[[0,0,1],[-12,-2,1],[0,0,1]],[[0,0,1],[0,4,1.04],[0,-4,1.07],[0,0,1]],[[0,0,1],[3,-5,1],[-3,3,1],[3,-4,1],[0,0,1]]][i];r.animate(k.map(([rot,y,s])=>({transform:`translateY(${y}px) rotate(${rot}deg) scale(${s})`})),{duration:1800+i*60,easing:'ease-in-out'});}
