/* DaBin design fixture. Isolated browser storage; no native archive access. */
const KEY='dabin:open-design-v3:fixture:1', TODAY='2026-09-30', ASSETS='open-design-v3/assets/';
const icons={inbox:'M3 4h18v15H3z M3 12h5l2 3h4l2-3h5',sun:'M12 3v2 M12 19v2 M3 12h2 M19 12h2 M5.6 5.6l1.4 1.4 M17 17l1.4 1.4 M5.6 18.4L7 17 M17 7l1.4-1.4 M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0',folder:'M3 6h6l2 2h10v12H3z M3 6V4h7l2 2h7v2',history:'M4 7V3 M4 7h4 M4 7a9 9 0 1 1-1 8 M12 7v5l3 2',search:'M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0 M15 15l6 6',plus:'M12 5v14 M5 12h14',gear:'M10 3h4l1 3 3-1 3 3-1 3 1 3-3 3-3-1-1 3h-4l-1-3-3 1-3-3 1-3-1-3 3-3 3 1z M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0',x:'M6 6l12 12 M18 6L6 18',expand:'M4 9V4h5 M15 4h5v5 M20 15v5h-5 M9 20H4v-5',copy:'M8 8h12v13H8z M16 8V3H3v13h5',text:'M4 5h16 M4 10h16 M4 15h10 M4 20h7',link:'M10 13l4-4 M9 7l3-3a5 5 0 0 1 7 7l-3 3 M15 17l-3 3a5 5 0 0 1-7-7l3-3',file:'M5 3h9l5 5v13H5z M14 3v6h5 M8 13h8 M8 17h6',image:'M3 4h18v16H3z M3 16l6-6 5 5 3-3 4 4 M17 8h.01',check:'M5 12l4 4L19 6',task:'M9 4h11 M9 12h11 M9 20h11 M3 4h1 M3 12h1 M3 20h1',arrow:'M5 12h14 M14 7l5 5-5 5',back:'M19 12H5 M10 7l-5 5 5 5',down:'M6 9l6 6 6-6',more:'M5 12h.01 M12 12h.01 M19 12h.01',clock:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0 M12 7v5l3 2',clip:'M9 12l6-6a3 3 0 0 1 4 4l-9 9a5 5 0 0 1-7-7l9-9 M6 15l9-9',pin:'M8 3h8 M9 3v5l-4 6h14l-4-6V3 M12 14v7',shelf:'M3 5h18v14H3z M3 14h18 M8 5v9 M15 5v9',note:'M4 3h16v18H4z M8 7h8 M8 11h8 M8 15h6',shield:'M12 3l8 3v6c0 4-4 7-8 9-4-2-8-5-8-9V6z M8 12l3 3 5-6',trash:'M3 6h18 M9 6V3h6v3 M5 6l1 15h12l1-15 M10 10v7 M14 10v7',download:'M12 3v12 M7 10l5 5 5-5 M4 16v5h16v-5',upload:'M12 16V4 M7 9l5-5 5 5 M4 16v5h16v-5',play:'M8 4l13 8-13 8z',pause:'M8 4v16 M16 4v16',filter:'M3 5h18 M7 12h10 M10 19h4',calendar:'M3 5h18v16H3z M7 3v5 M17 3v5 M3 11h18',bell:'M5 17h14l-2-3V9a5 5 0 0 0-10 0v5z M10 21h4',refresh:'M20 8V3 M20 8h-5 M4 16v5 M4 16h5 M20 8a8 8 0 0 0-14-3 M4 16a8 8 0 0 0 14 3',minus:'M5 12h14',grip:'M9 5h.01 M15 5h.01 M9 12h.01 M15 12h.01 M9 19h.01 M15 19h.01',external:'M14 3h7v7 M21 3l-11 11 M10 3H3v18h18v-7',info:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0 M12 11v6 M12 7h.01'};
const ic=n=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[n]||icons.file}"/></svg>`;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fixture=()=>({version:1,project:'all',projects:['Northstar Studio','Mori / 森','Personal'],filter:'All',date:TODAY,scope:'Day',query:'',source:'all',origin:'all',dateFilter:'all',pinned:false,clipboardTab:'Recent',todayTab:'Today',drafts:{},notes:{'Northstar Studio':{text:'Northstar — next conversation\n\nThe quieter direction is working. Let the product do more of the talking.\n\nTo discuss\n• A little more space around the headline\n• One strong image, fewer small details\n• Check the final English, Hebrew and Japanese copy\n\nשומרים על הדברים החשובים.\n大切なもののための余白。',updated:TODAY},unfiled:{text:'A place for the things I haven’t found a home for yet.',updated:TODAY}},settings:{dark:false,accent:'#6D5387',opacity:100,tooltips:true,quiet:false,reduceMotion:false,reduceTransparency:false,contrast:false,clipboard:false,screenshots:false,paused:false,folder:'',exclusions:['DaBin','1Password','Keychain Access'],retention:'Never',linkPreviews:false,home:'Top right',globalSearch:'⌃⌥Space',globalCapture:'⌃⌥V'},items:[
{id:'feedback',type:'Text',title:'A little more breathing room',text:'The quieter direction feels right. Keep the headline, make the product image a little larger, and give the final call to action more room.',source:'Mail',date:TODAY,time:'14:32',project:'Northstar Studio',inbox:true,comment:'Bring this into the next design review.',origin:'manual'},
{id:'study',type:'Media',title:'Northstar · visual direction 02',text:'Make room for what matters. A quieter direction. A clearer beginning.',source:'Finder',date:TODAY,time:'14:18',project:'Northstar Studio',image:ASSETS+'northstar-study.svg',filename:'Northstar_direction-02_EN-HE-日本語.svg',inbox:true,shelf:true,origin:'manual'},
{id:'review',type:'Text',title:'Prepare the Northstar review',text:'Review the headline, image credits and final attachments before the client meeting.',source:'Notes',date:'2026-09-29',time:'16:40',project:'Northstar Studio',inbox:true,task:true,planned:TODAY,priority:'High',effort:45,deadline:'2026-10-01T16:00',repeat:'None',order:0,checklist:[{text:'Check English, Hebrew and Japanese copy',done:false},{text:'Confirm the exported filenames',done:true}],attachments:['brief'],comment:'Keep the original feedback beside the work plan.',origin:'manual'},
{id:'batch',type:'Files',title:'Everything for the next review',text:'Two files, kept together.',source:'Finder',date:TODAY,time:'13:54',project:'Northstar Studio',inbox:true,members:['brief','copy'],origin:'manual'},
{id:'brief',type:'Files',title:'Northstar — client feedback',text:'The quieter direction feels right. Keep the headline, make the product image a little larger, and give the final call to action more room.',filename:'Northstar_client-feedback.txt',url:ASSETS+'client-feedback.txt',source:'Finder',date:TODAY,time:'13:54',project:'Northstar Studio',parent:'review',origin:'manual',indexed:'The quieter direction feels right. Keep the headline, make the product image a little larger.'},
{id:'copy',type:'Text',title:'Review copy · EN / HE / 日本語',text:'Make room for what matters.\nמקום לדברים החשובים.\n大切なもののための余白。',source:'Notes',date:TODAY,time:'13:54',project:'Northstar Studio',origin:'manual'},
{id:'link',type:'Links',title:'A reference worth coming back to',text:'https://developer.apple.com/design/human-interface-guidelines',url:'https://developer.apple.com/design/human-interface-guidelines',source:'Safari',date:TODAY,time:'11:42',project:'Northstar Studio',inbox:true,shelf:true,origin:'manual'},
{id:'snippet',type:'Text',title:'A warm sign-off',text:'Thanks for the thoughtful feedback. I’ll bring an updated direction to our next review.',source:'Mail',date:'2026-09-28',time:'10:12',project:'Northstar Studio',snippet:'Client sign-off',pinned:true,origin:'clipboard'},
{id:'mori',type:'Text',title:'Collect packaging references',text:'Look for quieter type and a simple, reusable structure.',source:'Safari',date:'2026-09-28',time:'09:20',project:'Mori / 森',task:true,planned:'2026-10-01',effort:30,priority:'Medium',checklist:[],origin:'manual'},
{id:'invoice',type:'Text',title:'Send the monthly studio summary',text:'Summarize the work and send it with the invoice.',source:'Notes',date:'2026-09-27',time:'15:10',project:'Northstar Studio',task:true,planned:TODAY,effort:20,priority:'Low',repeat:'Monthly',checklist:[{text:'Check the project summary',done:false}],attachments:[],order:1,origin:'manual'},
{id:'done',type:'Media',title:'Save the approved visual direction',text:'The first direction is saved with the project.',image:ASSETS+'northstar-study.svg',source:'Finder',date:'2026-09-29',time:'12:20',project:'Northstar Studio',task:true,completed:true,planned:'2026-09-29',shelf:true,origin:'manual'},
{id:'followup',type:'Text',title:'Ask about the photo credits',text:'Check that the final image credits are approved.',date:TODAY,time:'09:00',project:'Northstar Studio',reminder:'2026-09-30T09:00:00',origin:'manual'},
{id:'trash-example',type:'Text',title:'Earlier headline idea',text:'A little space for something new.',date:'2026-09-26',time:'11:13',project:null,deleted:'2026-09-29',origin:'manual'},
...['A softer introduction','Keep the useful parts','Reference for the review','One image is enough'].map((title,i)=>({id:'auto'+i,type:'Text',title,text:title,source:'Notes',date:TODAY,time:'10:'+String(12+i*9),origin:'clipboard',auto:true,inbox:false}))]});
let state;try{state=JSON.parse(localStorage.getItem(KEY))||fixture()}catch{state=fixture()}
const PAGE=document.body.dataset.page, $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)], param=new URLSearchParams(location.search);
let currentId=param.get('id')||(['task-detail','reminder'].includes(PAGE)?'review':'feedback'), busy=false,lastFocus,toastTimer;
const item=id=>state.items.find(x=>x.id===id), current=()=>item(currentId), alive=()=>state.items.filter(x=>!x.deleted), projectItems=()=>alive().filter(x=>state.project==='all'||(x.project||'unfiled')===state.project), dayAdd=(d,n)=>{let x=new Date(d+'T12:00:00');x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)}, dayLabel=d=>new Date(d+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'}), fullDay=d=>new Date(d+'T12:00:00').toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'});
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));return true}catch{toast('Couldn’t save. Browser storage is full or unavailable. Your edits are still on screen.',true);return false}}
function change(fn,paint=true){const old=JSON.stringify(state);fn();if(!save()){state=JSON.parse(old);return false}if(paint)render();return true}
function toast(text,error=false,extra=''){let t=$('#toast');t.innerHTML=esc(text)+extra;t.classList.add('visible');t.setAttribute('role',error?'alert':'status');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('visible'),6500)}
function go(page,params=''){saveContext();location.href=page+'.html'+params}
function saveContext(){try{sessionStorage.setItem('dabin:context:'+PAGE,JSON.stringify({scroll:$('.main')?.scrollTop||0}));if(!['capture-detail','task-detail','reminder','export','new-note','new-task','settings'].includes(PAGE))sessionStorage.setItem('dabin:return',location.href);sessionStorage.setItem('dabin:last',location.href)}catch{}}
function back(){saveContext();let target;try{target=sessionStorage.getItem('dabin:return')}catch{}location.href=target&&target!==location.href?target:'inbox.html'}
function matches(x){return (state.filter==='All'||state.filter==='Tasks'&&x.task||state.filter===x.type)&&(!state.pinned||x.pinned)&&(state.source==='all'||x.source===state.source)&&(state.origin==='all'||x.origin===state.origin)&&(state.dateFilter==='all'||x.date===(state.dateFilter==='Today'?TODAY:dayAdd(TODAY,-1)))}
function safeURL(v){try{const u=new URL(v,location.href);return ['http:','https:','file:'].includes(u.protocol)?u.href:'#'}catch{return '#'}}
function taskRoute(x){return (x.task?'task-detail':'capture-detail')+'.html?id='+encodeURIComponent(x.id)}
function autoLabel(){let s=state.settings;return !s.clipboard&&!s.screenshots?'Auto capture off':s.paused?'Auto capture paused':s.screenshots&&!s.folder?'Folder access needed':'Auto capture on'}
function applyTheme(){const s=state.settings,root=document.documentElement;root.dataset.theme=s.dark?'dark':'light';root.style.setProperty('--body-opacity',s.reduceTransparency?1:s.opacity/100);let c=s.accent;const rgb=h=>[1,3,5].map(i=>parseInt(h.slice(i,i+2),16)/255),lum=a=>a.map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4).reduce((a,v,i)=>a+v*[.2126,.7152,.0722][i],0),bg=rgb(s.dark?'#2d2a30':'#f3f1f5');let a=rgb(c);if(s.dark&&c.toLowerCase()==='#6d5387')a=rgb('#ab92c6');for(let k=0;k<100;k++){let l1=lum(a),l2=lum(bg);if((Math.max(l1,l2)+.05)/(Math.min(l1,l2)+.05)>=4.6)break;a=a.map(v=>s.dark?v+(1-v)*.04:v*.96)}a=a.map(v=>Math.round(v*255)/255);root.style.setProperty('--accent',`rgb(${a.map(v=>Math.round(v*255)).join(',')})`);const whiteContrast=1.05/(lum(a)+.05),darkContrast=(lum(a)+.05)/(lum(rgb('#1d1c21'))+.05);root.style.setProperty('--on-accent',darkContrast>whiteContrast?'#1d1c21':'#ffffff');root.classList.toggle('reduce-motion',s.reduceMotion);root.classList.toggle('high-contrast',s.contrast);}
function openDialog(title,body,actions=''){lastFocus=document.activeElement;let d=$('#dialog');d.innerHTML=`<div class="row between"><h2>${esc(title)}</h2><button class="icon-btn" data-action="close-dialog" aria-label="Close dialog">${ic('x')}</button></div>${body}${actions?'<div class="actions">'+actions+'</div>':''}`;d.showModal();setTimeout(()=>$('input,textarea,select,button',d)?.focus(),0)}
function closeDialog(){$('#dialog').close();lastFocus?.focus()}
function button(text,action,cls='',id=''){return `<button type="button" class="btn ${cls}" data-action="${action}"${id?' data-id="'+esc(id)+'"':''}>${text}</button>`}
function native(title,body){openDialog(title,`<div class="native-label">Native interaction · browser simulation</div><p style="margin-top:14px">${body}</p><p>The prototype does not access the native archive, system permissions or other applications.</p>`,button('Got it','close-dialog','primary'))}
function download(name,content,type='text/plain;charset=utf-8'){let u=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),3000)}
async function copyText(text){try{await navigator.clipboard.writeText(text);toast('Copied to clipboard');return true}catch{openDialog('Copy content',`<p>Clipboard access is unavailable here. Select and copy the content below.</p><textarea rows="7" readonly>${esc(text)}</textarea>`,button('Close','close-dialog'));$('textarea',$('#dialog')).select();return false}}
function createCapture(text,task=false){text=text.trim();if(!text)return false;const now=new Date(),x={id:'capture-'+Date.now(),title:text.split('\n')[0].slice(0,180),text,type:/^https?:\/\/\S+$/.test(text)?'Links':'Text',url:/^https?:\/\/\S+$/.test(text)?text:undefined,date:TODAY,time:now.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'}),project:state.project==='all'||state.project==='unfiled'?null:state.project,inbox:true,origin:'manual',task,checklist:[],attachments:[]};if(!change(()=>{state.items.unshift(x);delete state.drafts[PAGE==='robot'?'inbox':PAGE]},false))return false;return x}
function celebrate(){if(!state.settings.quiet){$('.frame')?.classList.add('saved-reaction');setTimeout(()=>$('.frame')?.classList.remove('saved-reaction'),750)}}
function trash(id){let x=item(id);if(!x)return;change(()=>{x.deleted=new Date().toISOString();(x.attachments||[]).forEach(i=>{if(item(i))item(i).deleted=x.deleted});state.lastDeleted=id});toast('Moved to Recently Deleted',false,'<button data-action="undo">Undo</button>')}
function restore(id){let x=item(id);change(()=>{delete x.deleted;(x.attachments||[]).forEach(i=>{if(item(i))delete item(i).deleted})});toast('Capture restored. Past reminders need a new time.')}
function recurrenceDate(x){const base=x.recurrenceAnchor||x.planned||TODAY, b=new Date(base+'T12:00:00'), now=new Date(TODAY+'T12:00:00');let next=new Date(b);if(x.repeat==='Monthly'){for(let n=1;n<1200;n++){const y=b.getFullYear(),m=b.getMonth()+n,d=Math.min(b.getDate(),new Date(y,m+1,0).getDate());next=new Date(y,m,d,12);if(next>now)break}}else{do{next.setDate(next.getDate()+(x.repeat==='Weekly'?7:1))}while(next<=now||x.repeat==='Weekdays'&&[0,6].includes(next.getDay()))}return next.toISOString().slice(0,10)}
function toggleComplete(id){const x=item(id);if(!x)return;change(()=>{x.completed=!x.completed;if(x.completed){pauseFocus(x);x.completedAt=new Date().toISOString();if(x.repeat&&x.repeat!=='None'&&!x.next){const next={...x,id:'next-'+Date.now(),date:TODAY,time:new Date().toTimeString().slice(0,5),planned:recurrenceDate(x),recurrenceAnchor:x.recurrenceAnchor||x.planned||TODAY,completed:false,completedAt:null,attachments:[],checklist:(x.checklist||[]).map(s=>({...s,done:false})),previous:x.id,next:null,reminder:null,countdownEnd:null,focus:undefined,pasteHistory:[]};state.items.unshift(next);x.next=next.id}}});if(x.completed)celebrate();toast(x.completed?'Task completed'+(x.next?' · next occurrence planned':''):'Task reopened')}
function exportText(scope=state.scope){const end=state.date,start=scope==='Week'?dayAdd(end,-6):end;return alive().filter(x=>x.date>=start&&x.date<=end&&!(x.date===TODAY&&x.time>new Date().toTimeString().slice(0,5))).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(x=>`${x.date} ${x.time} · ${x.type}${x.source?' · '+x.source:''}\n${x.title}\n${x.text||x.indexed||'[No text preview available]'}\n`).join('\n')}
