/* Header project picker: local UI, existing shared project state. */
let projectSwitcherTrigger=0;
function selectedProjectLabel(){return state.project==='all'?'All projects':state.project==='unfiled'?'Unfiled':state.project}
function projectHeading(){return `<button type="button" class="project-heading" data-action="project-picker" aria-label="Switch project: ${esc(selectedProjectLabel())}" aria-haspopup="dialog" aria-expanded="false" aria-controls="project-switcher"><span class="project-heading-mark">${ic('folder')}</span><span class="project-heading-name">${esc(selectedProjectLabel())}</span>${ic('down')}</button>`}
function projectSwitcherMarkup(){return `<div id="project-switcher" popover="auto" role="dialog" aria-label="Projects"><label class="ps-search">${ic('search')}<input type="search" id="project-switcher-search" placeholder="Find a project…" aria-label="Find a project" aria-controls="project-switcher-list" autocomplete="off"></label><div class="ps-list" id="project-switcher-list" role="group" aria-label="Choose a project"></div><div class="ps-footer"><button type="button" class="ps-new" id="project-switcher-new">${ic('plus')}New project</button><form class="ps-create" id="project-switcher-create" hidden><label for="project-switcher-name">New project</label><div class="ps-create-row"><input id="project-switcher-name" placeholder="Project name" autocomplete="off" maxlength="180" aria-describedby="project-switcher-error"><button type="submit" aria-label="Create project" title="Create project">${ic('check')}</button><button type="button" id="project-switcher-cancel" aria-label="Cancel new project" title="Cancel">${ic('x')}</button></div><p class="ps-error" id="project-switcher-error" role="alert"></p></form></div></div>`}
function matchingProjects(query=''){const q=query.trim().toLocaleLowerCase();return ['all','unfiled',...state.projects].map(value=>({value,name:value==='all'?'All projects':value==='unfiled'?'Unfiled':value})).filter(p=>p.name.toLocaleLowerCase().includes(q))}
function paintProjectChoices(){const rows=matchingProjects($('#project-switcher-search').value);$('#project-switcher-list').innerHTML=rows.length?rows.map(p=>`<button type="button" class="ps-option" data-project-value="${esc(p.value)}" aria-pressed="${state.project===p.value}"><span class="ps-monogram">${p.value==='all'?ic('inbox'):p.value==='unfiled'?ic('folder'):esc(Array.from(p.name)[0]?.toLocaleUpperCase()||'')}</span><span class="ps-name">${esc(p.name)}</span><span class="ps-check">${state.project===p.value?ic('check'):''}</span></button>`).join(''):'<p class="ps-empty" role="status">No matching projects</p>'}
function positionProjectSwitcher(){
 const panel=$('#project-switcher');if(!panel?.matches(':popover-open'))return;
 const trigger=$$('[data-action="project-picker"]')[projectSwitcherTrigger]||$('.project-heading');if(!trigger)return;
 const viewport=viewportRect();panel.style.width=Math.min(332,Math.max(0,viewport.width-24))+'px';panel.style.maxHeight=Math.max(0,viewport.height-24)+'px';
 const r=projectPanelRect(trigger.getBoundingClientRect(),{width:panel.offsetWidth,height:panel.offsetHeight},viewport);
 panel.style.left=r.left+'px';panel.style.top=r.top+'px';
}
function openProjectSwitcher(trigger){const panel=$('#project-switcher');if(panel.matches(':popover-open')){panel.hidePopover();return}projectSwitcherTrigger=Math.max(0,$$('[data-action="project-picker"]').indexOf(trigger));$('#project-switcher-search').value='';$('#project-switcher-create').hidden=true;$('#project-switcher-new').hidden=false;paintProjectChoices();panel.showPopover();$$('[data-action="project-picker"]').forEach(b=>b.setAttribute('aria-expanded','true'));positionProjectSwitcher();$('#project-switcher-search').focus()}
function projectNameError(name){if(!name)return 'Enter a project name.';if(name.length>180)return 'Keep the name under 180 characters.';if(['all','all projects','unfiled','__new'].includes(name.toLocaleLowerCase())||state.projects.some(p=>p.toLocaleLowerCase()===name.toLocaleLowerCase()))return 'That name is already in use.';return ''}
function commitProjectSelection(name,create=false){if((create&&projectNameError(name))||(!create&&!['all','unfiled',...state.projects].includes(name)))return false;if(!change(()=>{if(create)state.projects.push(name);state.project=name},false))return false;$('#project-switcher').hidePopover();render();($$('[data-action="project-picker"]')[projectSwitcherTrigger]||$('.project-heading'))?.focus();return true}
function bindProjectSwitcher(){const panel=$('#project-switcher'),search=$('#project-switcher-search'),form=$('#project-switcher-create');
 search.addEventListener('input',()=>{paintProjectChoices();positionProjectSwitcher()});
 panel.addEventListener('toggle',()=>{const open=panel.matches(':popover-open');$$('[data-action="project-picker"]').forEach(b=>b.setAttribute('aria-expanded',String(open)))});
 panel.addEventListener('click',e=>{const row=e.target.closest('[data-project-value]');if(row)commitProjectSelection(row.dataset.projectValue)});
 $('#project-switcher-new').addEventListener('click',()=>{form.hidden=false;$('#project-switcher-new').hidden=true;$('#project-switcher-name').value=search.value.trim();$('#project-switcher-name').removeAttribute('aria-invalid');$('#project-switcher-error').textContent='';positionProjectSwitcher();$('#project-switcher-name').focus()});
 $('#project-switcher-cancel').addEventListener('click',()=>{form.hidden=true;$('#project-switcher-new').hidden=false;positionProjectSwitcher();$('#project-switcher-new').focus()});
 $('#project-switcher-name').addEventListener('input',e=>{e.target.removeAttribute('aria-invalid');$('#project-switcher-error').textContent=''});
 form.addEventListener('submit',e=>{e.preventDefault();e.stopPropagation();const input=$('#project-switcher-name'),name=input.value.trim().normalize('NFC'),error=projectNameError(name);if(error){$('#project-switcher-error').textContent=error;input.setAttribute('aria-invalid','true');input.focus();positionProjectSwitcher();return}if(!commitProjectSelection(name,true))$('#project-switcher-error').textContent='Could not save. Try again.'});
 panel.addEventListener('keydown',e=>{if(e.key==='Tab'){const controls=$$('input,button',panel).filter(el=>!el.closest('[hidden]')&&!el.disabled),first=controls[0],last=controls.at(-1);if(e.shiftKey&&e.target===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&e.target===last){e.preventDefault();first?.focus()}return}if(!['ArrowDown','ArrowUp','Enter'].includes(e.key)||e.target.closest('form'))return;const rows=$$('.ps-option',panel),index=rows.indexOf(document.activeElement);if(e.key==='Enter'&&e.target===search){e.preventDefault();rows[0]?.click()}else if(e.key!=='Enter'){e.preventDefault();const next=index<0?(e.key==='ArrowDown'?0:rows.length-1):(index+(e.key==='ArrowDown'?1:-1)+rows.length)%rows.length;rows[next]?.focus()}});
}
